load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "lexer_test",
    srcs = ["lexer_test.cc"],
    deps = [
        "//src/lib:lib",
        "@com_google_googletest//:gtest_main",
    ],
)
